
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 29 18:50:32 CST 2026
//----------------------------------------------------

package ejemplocup;

import java_cup.runtime.*;
import java.io.FileReader;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri May 29 18:50:32 CST 2026
  */
public class AnalizadorSemantico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSemantico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSemantico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSemantico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\056\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\004\011\000\002\004\011" +
    "\000\002\004\005\000\002\004\004\000\002\004\010\000" +
    "\002\004\014\000\002\024\005\000\002\024\003\000\002" +
    "\025\003\000\002\023\003\000\002\023\003\000\002\007" +
    "\005\000\002\007\003\000\002\020\005\000\002\020\003" +
    "\000\002\014\005\000\002\014\003\000\002\021\004\000" +
    "\002\021\006\000\002\022\003\000\002\022\006\000\002" +
    "\022\003\000\002\022\010\000\002\012\011\000\002\012" +
    "\002\000\002\005\006\000\002\005\002\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\013\005\000" +
    "\002\013\002\000\002\015\003\000\002\015\004\000\002" +
    "\015\004\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\010\003\000\002\011\003" +
    "\000\002\011\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\143\000\014\004\013\007\011\023\005\027\004\032" +
    "\010\001\002\000\006\030\115\031\116\001\002\000\004" +
    "\024\100\001\002\000\004\014\077\001\002\000\016\002" +
    "\uffff\004\uffff\007\uffff\023\uffff\027\uffff\032\uffff\001\002" +
    "\000\004\047\076\001\002\000\004\047\024\001\002\000" +
    "\016\002\067\004\013\007\011\023\005\027\004\032\010" +
    "\001\002\000\006\011\015\047\014\001\002\000\032\005" +
    "\uffd5\006\uffd5\012\uffd5\013\uffd5\014\uffd5\016\uffd5\022\064" +
    "\033\uffd5\035\uffd5\036\uffd5\037\uffd5\040\uffd5\001\002\000" +
    "\004\005\ufff4\001\002\000\004\005\023\001\002\000\006" +
    "\005\ufff3\013\021\001\002\000\010\005\ufff1\013\ufff1\016" +
    "\ufff1\001\002\000\004\047\014\001\002\000\010\005\ufff2" +
    "\013\ufff2\016\ufff2\001\002\000\004\047\024\001\002\000" +
    "\020\006\uffd6\010\uffd6\014\uffd6\015\uffd6\017\uffd6\021\uffd6" +
    "\033\uffd6\001\002\000\012\006\uffe5\014\uffe5\017\026\033" +
    "\uffe5\001\002\000\004\020\056\001\002\000\010\006\030" +
    "\014\uffe3\033\uffe3\001\002\000\004\047\014\001\002\000" +
    "\006\014\uffde\033\032\001\002\000\004\034\034\001\002" +
    "\000\004\014\ufffd\001\002\000\004\047\014\001\002\000" +
    "\006\013\uffed\014\uffed\001\002\000\006\013\042\014\uffdf" +
    "\001\002\000\012\013\uffdd\014\uffdd\035\040\036\041\001" +
    "\002\000\006\013\uffdc\014\uffdc\001\002\000\006\013\uffdb" +
    "\014\uffdb\001\002\000\004\047\014\001\002\000\006\013" +
    "\uffee\014\uffee\001\002\000\010\012\045\037\047\040\046" +
    "\001\002\000\012\045\uffe2\046\uffe2\047\uffe2\050\uffe2\001" +
    "\002\000\012\045\uffe0\046\uffe0\047\uffe0\050\uffe0\001\002" +
    "\000\012\045\uffe1\046\uffe1\047\uffe1\050\uffe1\001\002\000" +
    "\012\045\055\046\054\047\051\050\052\001\002\000\014" +
    "\006\uffd7\013\uffd7\014\uffd7\016\uffd7\033\uffd7\001\002\000" +
    "\014\006\uffd8\013\uffd8\014\uffd8\016\uffd8\033\uffd8\001\002" +
    "\000\006\014\uffe4\033\uffe4\001\002\000\014\006\uffd9\013" +
    "\uffd9\014\uffd9\016\uffd9\033\uffd9\001\002\000\014\006\uffda" +
    "\013\uffda\014\uffda\016\uffda\033\uffda\001\002\000\004\047" +
    "\024\001\002\000\004\021\060\001\002\000\004\047\014" +
    "\001\002\000\004\012\062\001\002\000\004\047\014\001" +
    "\002\000\010\006\uffe6\014\uffe6\033\uffe6\001\002\000\004" +
    "\047\065\001\002\000\030\005\uffd4\006\uffd4\012\uffd4\013" +
    "\uffd4\014\uffd4\016\uffd4\033\uffd4\035\uffd4\036\uffd4\037\uffd4" +
    "\040\uffd4\001\002\000\016\002\001\004\001\007\001\023" +
    "\001\027\001\032\001\001\002\000\004\002\000\001\002" +
    "\000\004\010\071\001\002\000\004\047\014\001\002\000" +
    "\004\012\073\001\002\000\012\045\055\046\054\047\051" +
    "\050\052\001\002\000\006\006\030\014\uffe3\001\002\000" +
    "\004\014\ufffc\001\002\000\004\014\ufffa\001\002\000\016" +
    "\002\ufffe\004\ufffe\007\ufffe\023\ufffe\027\ufffe\032\ufffe\001" +
    "\002\000\004\047\024\001\002\000\004\015\102\001\002" +
    "\000\004\047\014\001\002\000\006\013\021\016\104\001" +
    "\002\000\004\025\105\001\002\000\004\015\106\001\002" +
    "\000\012\045\055\046\054\047\051\050\052\001\002\000" +
    "\006\013\112\016\113\001\002\000\006\013\ufff5\016\ufff5" +
    "\001\002\000\006\013\ufff6\016\ufff6\001\002\000\012\045" +
    "\055\046\054\047\051\050\052\001\002\000\004\014\ufff8" +
    "\001\002\000\006\013\ufff7\016\ufff7\001\002\000\004\047" +
    "\145\001\002\000\004\047\024\001\002\000\004\015\120" +
    "\001\002\000\004\047\122\001\002\000\006\013\uffef\016" +
    "\uffef\001\002\000\010\026\130\041\132\042\131\001\002" +
    "\000\006\013\124\016\125\001\002\000\004\047\122\001" +
    "\002\000\004\014\ufff9\001\002\000\006\013\ufff0\016\ufff0" +
    "\001\002\000\010\013\uffec\016\uffec\043\143\001\002\000" +
    "\012\013\uffe8\015\136\016\uffe8\043\uffe8\001\002\000\004" +
    "\015\133\001\002\000\010\013\uffea\016\uffea\043\uffea\001" +
    "\002\000\004\045\134\001\002\000\004\016\135\001\002" +
    "\000\010\013\uffe9\016\uffe9\043\uffe9\001\002\000\004\045" +
    "\137\001\002\000\004\013\140\001\002\000\004\045\141" +
    "\001\002\000\004\016\142\001\002\000\010\013\uffe7\016" +
    "\uffe7\043\uffe7\001\002\000\004\044\144\001\002\000\006" +
    "\013\uffeb\016\uffeb\001\002\000\004\014\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\143\000\010\002\011\003\006\004\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\067\001\001\000" +
    "\006\003\065\004\005\001\001\000\010\007\016\011\017" +
    "\023\015\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\021\001\001\000\002\001\001\000\004\010\024\001" +
    "\001\000\002\001\001\000\004\012\026\001\001\000\002" +
    "\001\001\000\004\005\030\001\001\000\004\011\043\001" +
    "\001\000\004\013\032\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\036\014\035\015\034\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\011\036\015\042\001" +
    "\001\000\002\001\001\000\004\016\047\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\052\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\056\001\001\000\002\001\001\000\004\011\060\001\001" +
    "\000\002\001\001\000\004\011\062\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\071\001" +
    "\001\000\002\001\001\000\004\006\073\001\001\000\004" +
    "\005\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\100\001\001\000\002\001\001" +
    "\000\006\007\102\011\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\107\024\106" +
    "\025\110\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\107\025\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\116\001\001\000\002\001\001\000\006\020\122\021\120" +
    "\001\001\000\002\001\001\000\004\022\126\001\001\000" +
    "\002\001\001\000\004\021\125\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSemantico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSemantico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSemantico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }
   
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    public static void main(String[] args){
        try {
            AnalizadorSemantico asin = new AnalizadorSemantico(
                    new AnalizadorLexico( new FileReader(args[0])));
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados SQL***");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSemantico$actions {
  private final AnalizadorSemantico parser;

  /** Constructor */
  CUP$AnalizadorSemantico$actions(AnalizadorSemantico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSemantico$do_action(
    int                        CUP$AnalizadorSemantico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSemantico$parser,
    java.util.Stack            CUP$AnalizadorSemantico$stack,
    int                        CUP$AnalizadorSemantico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSemantico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSemantico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // nombre_compuesto ::= ID PUNTO ID 
            {
              Object RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id2; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // nombre_compuesto ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // nombre_tabla ::= ID 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = d; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_tabla",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // valor ::= ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=i; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // valor ::= LITERAL_STR 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=s; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // valor ::= NUREAL 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=n; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // valor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=e; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // elemento_order ::= nombre_compuesto DESC 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // elemento_order ::= nombre_compuesto ASC 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // elemento_order ::= nombre_compuesto 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // clausula_order ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_order",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // clausula_order ::= ORDER BY lista_order 
            {
              Object RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int loright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = lo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_order",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comparador ::= MENOR 
            {
              Object RESULT =null;
		 RESULT = "<"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comparador ::= MAYOR 
            {
              Object RESULT =null;
		 RESULT = ">"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // comparador ::= IGUAL 
            {
              Object RESULT =null;
		 RESULT = "="; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // clausula_where ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_where",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // clausula_where ::= WHERE nombre_compuesto comparador valor 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int cpleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int cpright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object cp = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = v; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_where",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // clausula_join ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_join",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // clausula_join ::= INNER JOIN nombre_tabla ON nombre_compuesto IGUAL nombre_compuesto 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nt; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_join",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_dato ::= FLOAT PAR_A ENTERO COMA ENTERO PAR_C 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = "FLOAT_DECIMAL"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_dato ::= VARCHAR PAR_A ENTERO PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = e; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_dato ::= INT 
            {
              Object RESULT =null;
		 RESULT = "INT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // columna ::= ID tipo_dato PRIMARY KEY 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		 RESULT = id; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // columna ::= ID tipo_dato 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_order ::= elemento_order 
            {
              Object RESULT =null;
		int eoleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object eo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = eo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_order",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_order ::= lista_order COMA elemento_order 
            {
              Object RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int loright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int eoleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object eo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = eo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_order",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_columnas ::= columna 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = c; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_columnas",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // lista_columnas ::= lista_columnas COMA columna 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = c; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_columnas",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_campos ::= nombre_compuesto 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_campos ::= lista_campos COMA nombre_compuesto 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // campos_select ::= lista_campos 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = lc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("campos_select",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // campos_select ::= ASTERISCO 
            {
              Object RESULT =null;
		 RESULT = "*"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("campos_select",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // elemento_valor ::= valor 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = v; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_valor",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_valores ::= elemento_valor 
            {
              Object RESULT =null;
		int evleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int evright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ev = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = ev; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_valores",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_valores ::= lista_valores COMA elemento_valor 
            {
              Object RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int evleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int evright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ev = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = ev; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_valores",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= INSERT INTO nombre_tabla PAR_A lista_campos PAR_C VALUES PAR_A lista_valores PAR_C 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).value;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).value;
		int lvleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = lv; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-9)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= CREATE TABLE nombre_tabla PAR_A lista_columnas PAR_C 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 
            VerificadorSemantico.verificarCreateTable(nt.toString());
            RESULT = lc;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= USE ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
            VerificadorSemantico.registrarUseDatabase(id.toString());
            RESULT = id;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= CREATE DATABASE ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
            VerificadorSemantico.registrarCreateDatabase(id.toString());
            RESULT = id;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= UPDATE nombre_tabla SET nombre_compuesto IGUAL valor clausula_where 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).value;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int cwleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cwright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object cw = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = v; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= SELECT campos_select FROM nombre_tabla clausula_join clausula_where clausula_order 
            {
              Object RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).right;
		Object cs = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).value;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int cjleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int cjright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object cj = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int cwleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int cwright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object cw = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int coleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int coright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object co = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = cs; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sentencia ::= instruccion PUNTOYCOMA 
            {
              Object RESULT =null;
		 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= sentencia 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSemantico$parser.done_parsing();
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // inicio ::= inicio sentencia 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

