/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

/* --------------------------Codigo de Usuario----------------------- */
package ejemplocup;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\2\0\1\3"+
    "\3\0\1\100\1\74\1\75\1\70\1\0\1\72\1\4\1\11\1\0"+
    "\1\5\11\6\1\0\1\73\1\77\1\71\1\76\2\0\1\43\1\60"+
    "\1\15\1\42\1\13\1\24\1\66\1\35\1\50\1\54\1\64\1\14"+
    "\1\27\1\51\1\26\1\41\1\7\1\25\1\12\1\16\1\40\1\56"+
    "\1\34\1\7\1\61\1\7\4\0\1\10\1\0\1\47\1\62\1\22"+
    "\1\46\1\20\1\30\1\67\1\37\1\52\1\55\1\65\1\21\1\33"+
    "\1\53\1\32\1\45\1\7\1\31\1\17\1\23\1\44\1\57\1\36"+
    "\1\7\1\63\1\7\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\2\3\1\4\1\5\44\4"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\1\1\16\14\4\1\17\1\20\4\4\1\17\7\4"+
    "\1\21\7\4\1\21\14\4\1\22\4\4\1\0\1\23"+
    "\1\4\1\24\23\4\1\25\5\4\1\26\1\4\1\27"+
    "\7\4\1\30\1\4\1\31\2\4\1\30\10\4\1\32"+
    "\13\4\1\33\13\4\1\34\11\4\1\35\1\4\1\36"+
    "\2\4\1\37\10\4\1\40\1\41\2\4\1\42\2\4"+
    "\1\43\2\4\1\44\13\4\1\45\5\4\1\46\1\47"+
    "\1\50\4\4\1\51\10\4\1\52\1\53\2\4\1\54"+
    "\2\4\1\55\1\56\4\4\1\57\2\4\1\60\6\4"+
    "\1\61\10\4\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\101\0\303\0\u0104\0\u0145\0\u0186"+
    "\0\101\0\u01c7\0\u0208\0\u0249\0\u028a\0\u02cb\0\u030c\0\u034d"+
    "\0\u038e\0\u03cf\0\u0410\0\u0451\0\u0492\0\u04d3\0\u0514\0\u0555"+
    "\0\u0596\0\u05d7\0\u0618\0\u0659\0\u069a\0\u06db\0\u071c\0\u075d"+
    "\0\u079e\0\u07df\0\u0820\0\u0861\0\u08a2\0\u08e3\0\u0924\0\u0965"+
    "\0\u09a6\0\u09e7\0\u0a28\0\u0a69\0\u0aaa\0\101\0\101\0\101"+
    "\0\101\0\101\0\101\0\101\0\101\0\u0aeb\0\u0b2c\0\u0b6d"+
    "\0\u0bae\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3\0\u0d34\0\u0d75"+
    "\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\u0186\0\u0eba\0\u0efb\0\u0f3c"+
    "\0\u0f7d\0\u0fbe\0\u0fff\0\u1040\0\u1081\0\u10c2\0\u1103\0\u1144"+
    "\0\u1185\0\u11c6\0\u1207\0\u1248\0\u1289\0\u12ca\0\u130b\0\u134c"+
    "\0\u138d\0\u13ce\0\u140f\0\u1450\0\u1491\0\u14d2\0\u1513\0\u1554"+
    "\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699\0\u16da\0\u0186\0\u171b"+
    "\0\u175c\0\u179d\0\u17de\0\u0aeb\0\101\0\u181f\0\u0186\0\u1860"+
    "\0\u18a1\0\u18e2\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27\0\u1a68"+
    "\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f\0\u1c70"+
    "\0\u1cb1\0\u1cf2\0\u0186\0\u1d33\0\u1d74\0\u1db5\0\u1df6\0\u1e37"+
    "\0\u0186\0\u1e78\0\u0186\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c\0\u1fbd"+
    "\0\u1ffe\0\u203f\0\u2080\0\u20c1\0\u0186\0\u2102\0\u2143\0\u2184"+
    "\0\u21c5\0\u2206\0\u2247\0\u2288\0\u22c9\0\u230a\0\u234b\0\u238c"+
    "\0\u0186\0\u23cd\0\u240e\0\u244f\0\u2490\0\u24d1\0\u2512\0\u2553"+
    "\0\u2594\0\u25d5\0\u2616\0\u2657\0\u0186\0\u2698\0\u26d9\0\u271a"+
    "\0\u275b\0\u279c\0\u27dd\0\u281e\0\u285f\0\u28a0\0\u28e1\0\u2922"+
    "\0\u0186\0\u2963\0\u29a4\0\u29e5\0\u2a26\0\u2a67\0\u2aa8\0\u2ae9"+
    "\0\u2b2a\0\u2b6b\0\u0186\0\u2bac\0\u0186\0\u2bed\0\u2c2e\0\u0186"+
    "\0\u2c6f\0\u2cb0\0\u2cf1\0\u2d32\0\u2d73\0\u2db4\0\u2df5\0\u2e36"+
    "\0\u0186\0\u0186\0\u2e77\0\u2eb8\0\u0186\0\u2ef9\0\u2f3a\0\u0186"+
    "\0\u2f7b\0\u2fbc\0\u0186\0\u2ffd\0\u303e\0\u307f\0\u30c0\0\u3101"+
    "\0\u3142\0\u3183\0\u31c4\0\u3205\0\u3246\0\u3287\0\u0186\0\u32c8"+
    "\0\u3309\0\u334a\0\u338b\0\u33cc\0\u0186\0\u0186\0\u0186\0\u340d"+
    "\0\u344e\0\u348f\0\u34d0\0\u0186\0\u3511\0\u3552\0\u3593\0\u35d4"+
    "\0\u3615\0\u3656\0\u3697\0\u36d8\0\u0186\0\u0186\0\u3719\0\u375a"+
    "\0\u0186\0\u379b\0\u37dc\0\u0186\0\u0186\0\u381d\0\u385e\0\u389f"+
    "\0\u38e0\0\u0186\0\u3921\0\u3962\0\u0186\0\u39a3\0\u39e4\0\u3a25"+
    "\0\u3a66\0\u3aa7\0\u3ae8\0\u0186\0\u3b29\0\u3b6a\0\u3bab\0\u3bec"+
    "\0\u3c2d\0\u3c6e\0\u3caf\0\u3cf0\0\u0186";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\2\10\1\13\1\14\1\15\2\10\1\16"+
    "\1\17\1\20\1\21\1\22\1\10\1\23\1\24\1\25"+
    "\1\10\1\26\1\10\1\27\1\10\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\10\1\51"+
    "\1\10\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\103\0\1\4"+
    "\102\0\1\4\105\0\1\67\74\0\2\7\2\0\1\67"+
    "\74\0\4\10\1\0\56\10\16\0\4\10\1\0\1\10"+
    "\1\70\54\10\16\0\4\10\1\0\13\10\1\71\1\72"+
    "\41\10\16\0\4\10\1\0\31\10\1\73\24\10\16\0"+
    "\4\10\1\0\6\10\1\74\47\10\16\0\4\10\1\0"+
    "\17\10\1\75\1\76\35\10\16\0\4\10\1\0\35\10"+
    "\1\77\20\10\16\0\4\10\1\0\2\10\1\100\10\10"+
    "\1\101\1\102\41\10\16\0\4\10\1\0\1\10\1\103"+
    "\54\10\16\0\4\10\1\0\13\10\1\104\23\10\1\105"+
    "\16\10\16\0\4\10\1\0\7\10\1\106\7\10\1\107"+
    "\1\110\35\10\16\0\4\10\1\0\6\10\1\111\47\10"+
    "\16\0\4\10\1\0\17\10\1\112\21\10\1\105\14\10"+
    "\16\0\4\10\1\0\23\10\1\113\32\10\16\0\4\10"+
    "\1\0\25\10\1\114\30\10\16\0\4\10\1\0\1\115"+
    "\26\10\1\116\26\10\16\0\4\10\1\0\13\10\1\117"+
    "\42\10\16\0\4\10\1\0\1\10\1\120\27\10\1\121"+
    "\24\10\16\0\4\10\1\0\1\122\25\10\1\123\10\10"+
    "\1\124\16\10\16\0\4\10\1\0\5\10\1\125\25\10"+
    "\1\126\22\10\16\0\4\10\1\0\17\10\1\127\36\10"+
    "\16\0\4\10\1\0\6\10\1\130\26\10\1\131\20\10"+
    "\16\0\4\10\1\0\5\10\1\132\24\10\1\133\6\10"+
    "\1\134\14\10\16\0\4\10\1\0\37\10\1\135\16\10"+
    "\16\0\4\10\1\0\14\10\1\136\11\10\1\137\27\10"+
    "\16\0\4\10\1\0\41\10\1\140\14\10\16\0\4\10"+
    "\1\0\20\10\1\141\11\10\1\142\23\10\16\0\4\10"+
    "\1\0\14\10\1\143\41\10\16\0\4\10\1\0\20\10"+
    "\1\144\35\10\16\0\4\10\1\0\31\10\1\145\24\10"+
    "\16\0\4\10\1\0\35\10\1\146\20\10\16\0\4\10"+
    "\1\0\47\10\1\147\6\10\16\0\4\10\1\0\51\10"+
    "\1\147\4\10\16\0\4\10\1\0\1\10\1\150\54\10"+
    "\16\0\4\10\1\0\6\10\1\151\47\10\16\0\4\10"+
    "\1\0\13\10\1\152\42\10\16\0\4\10\1\0\17\10"+
    "\1\153\36\10\11\0\100\154\1\155\5\0\2\67\77\0"+
    "\4\10\1\0\2\10\1\156\1\10\1\157\51\10\16\0"+
    "\4\10\1\0\1\10\1\160\54\10\16\0\4\10\1\0"+
    "\26\10\1\161\27\10\16\0\4\10\1\0\46\10\1\162"+
    "\7\10\16\0\4\10\1\0\7\10\1\163\1\10\1\157"+
    "\44\10\16\0\4\10\1\0\6\10\1\164\47\10\16\0"+
    "\4\10\1\0\32\10\1\165\23\10\16\0\4\10\1\0"+
    "\50\10\1\166\5\10\16\0\4\10\1\0\14\10\1\167"+
    "\41\10\16\0\4\10\1\0\14\10\1\170\41\10\16\0"+
    "\4\10\1\0\13\10\1\171\42\10\16\0\4\10\1\0"+
    "\12\10\1\172\43\10\16\0\4\10\1\0\30\10\1\173"+
    "\25\10\16\0\4\10\1\0\20\10\1\174\35\10\16\0"+
    "\4\10\1\0\20\10\1\175\35\10\16\0\4\10\1\0"+
    "\17\10\1\176\36\10\16\0\4\10\1\0\16\10\1\177"+
    "\37\10\16\0\4\10\1\0\34\10\1\200\21\10\16\0"+
    "\4\10\1\0\1\10\1\201\54\10\16\0\4\10\1\0"+
    "\6\10\1\202\47\10\16\0\4\10\1\0\1\10\1\203"+
    "\54\10\16\0\4\10\1\0\30\10\1\204\25\10\16\0"+
    "\4\10\1\0\36\10\1\205\17\10\16\0\4\10\1\0"+
    "\1\206\2\10\1\207\52\10\16\0\4\10\1\0\4\10"+
    "\1\210\51\10\16\0\4\10\1\0\3\10\1\211\52\10"+
    "\16\0\4\10\1\0\4\10\1\212\51\10\16\0\4\10"+
    "\1\0\30\10\1\213\25\10\16\0\4\10\1\0\6\10"+
    "\1\203\47\10\16\0\4\10\1\0\34\10\1\214\21\10"+
    "\16\0\4\10\1\0\40\10\1\215\15\10\16\0\4\10"+
    "\1\0\5\10\1\216\2\10\1\217\45\10\16\0\4\10"+
    "\1\0\11\10\1\220\44\10\16\0\4\10\1\0\10\10"+
    "\1\211\45\10\16\0\4\10\1\0\11\10\1\221\44\10"+
    "\16\0\4\10\1\0\34\10\1\213\21\10\16\0\4\10"+
    "\1\0\1\222\3\10\1\223\32\10\1\224\16\10\16\0"+
    "\4\10\1\0\4\10\1\225\51\10\16\0\4\10\1\0"+
    "\2\10\1\226\53\10\16\0\4\10\1\0\5\10\1\227"+
    "\3\10\1\230\27\10\1\231\14\10\16\0\4\10\1\0"+
    "\11\10\1\225\44\10\16\0\4\10\1\0\7\10\1\232"+
    "\46\10\16\0\4\10\1\0\36\10\1\233\17\10\16\0"+
    "\4\10\1\0\40\10\1\234\15\10\16\0\4\10\1\0"+
    "\2\10\1\235\10\10\1\236\42\10\16\0\4\10\1\0"+
    "\7\10\1\237\7\10\1\240\36\10\16\0\4\10\1\0"+
    "\47\10\1\241\6\10\16\0\4\10\1\0\51\10\1\241"+
    "\4\10\16\0\4\10\1\0\14\10\1\242\41\10\16\0"+
    "\4\10\1\0\20\10\1\243\35\10\16\0\4\10\1\0"+
    "\1\10\1\244\54\10\16\0\4\10\1\0\31\10\1\245"+
    "\24\10\16\0\4\10\1\0\37\10\1\246\16\10\16\0"+
    "\4\10\1\0\2\10\1\247\53\10\16\0\4\10\1\0"+
    "\6\10\1\250\47\10\16\0\4\10\1\0\35\10\1\251"+
    "\20\10\16\0\4\10\1\0\41\10\1\252\14\10\16\0"+
    "\4\10\1\0\7\10\1\253\46\10\16\0\4\10\1\0"+
    "\31\10\1\254\24\10\16\0\4\10\1\0\15\10\1\255"+
    "\40\10\16\0\4\10\1\0\1\10\1\256\54\10\16\0"+
    "\4\10\1\0\1\10\1\257\54\10\16\0\4\10\1\0"+
    "\1\10\1\260\54\10\16\0\4\10\1\0\35\10\1\261"+
    "\20\10\16\0\4\10\1\0\21\10\1\255\34\10\16\0"+
    "\4\10\1\0\6\10\1\262\47\10\16\0\4\10\1\0"+
    "\6\10\1\263\47\10\16\0\4\10\1\0\6\10\1\264"+
    "\47\10\16\0\4\10\1\0\13\10\1\265\42\10\16\0"+
    "\4\10\1\0\17\10\1\266\36\10\16\0\4\10\1\0"+
    "\31\10\1\267\24\10\16\0\4\10\1\0\15\10\1\270"+
    "\40\10\16\0\4\10\1\0\3\10\1\271\52\10\16\0"+
    "\4\10\1\0\36\10\1\272\17\10\16\0\4\10\1\0"+
    "\31\10\1\273\24\10\16\0\4\10\1\0\14\10\1\274"+
    "\41\10\16\0\4\10\1\0\35\10\1\275\20\10\16\0"+
    "\4\10\1\0\21\10\1\276\34\10\16\0\4\10\1\0"+
    "\10\10\1\271\45\10\16\0\4\10\1\0\40\10\1\277"+
    "\15\10\16\0\4\10\1\0\35\10\1\300\20\10\16\0"+
    "\4\10\1\0\20\10\1\301\35\10\16\0\4\10\1\0"+
    "\1\10\1\302\54\10\16\0\4\10\1\0\14\10\1\303"+
    "\41\10\16\0\4\10\1\0\1\10\1\304\54\10\16\0"+
    "\4\10\1\0\2\10\1\305\53\10\16\0\4\10\1\0"+
    "\6\10\1\306\47\10\16\0\4\10\1\0\20\10\1\303"+
    "\35\10\16\0\4\10\1\0\6\10\1\307\47\10\16\0"+
    "\4\10\1\0\7\10\1\305\46\10\16\0\4\10\1\0"+
    "\37\10\1\310\16\10\16\0\4\10\1\0\41\10\1\310"+
    "\14\10\16\0\4\10\1\0\26\10\1\311\27\10\16\0"+
    "\4\10\1\0\3\10\1\312\52\10\16\0\4\10\1\0"+
    "\32\10\1\313\23\10\16\0\4\10\1\0\10\10\1\314"+
    "\45\10\16\0\4\10\1\0\26\10\1\315\27\10\16\0"+
    "\4\10\1\0\32\10\1\316\23\10\16\0\4\10\1\0"+
    "\3\10\1\317\52\10\16\0\4\10\1\0\4\10\1\320"+
    "\51\10\16\0\4\10\1\0\4\10\1\321\51\10\16\0"+
    "\4\10\1\0\1\10\1\322\54\10\16\0\4\10\1\0"+
    "\10\10\1\323\45\10\16\0\4\10\1\0\11\10\1\324"+
    "\44\10\16\0\4\10\1\0\11\10\1\321\44\10\16\0"+
    "\4\10\1\0\6\10\1\322\47\10\16\0\4\10\1\0"+
    "\4\10\1\325\51\10\16\0\4\10\1\0\36\10\1\326"+
    "\17\10\16\0\4\10\1\0\13\10\1\327\42\10\16\0"+
    "\4\10\1\0\13\10\1\330\42\10\16\0\4\10\1\0"+
    "\11\10\1\325\44\10\16\0\4\10\1\0\40\10\1\331"+
    "\15\10\16\0\4\10\1\0\17\10\1\332\36\10\16\0"+
    "\4\10\1\0\17\10\1\330\36\10\16\0\4\10\1\0"+
    "\1\10\1\333\54\10\16\0\4\10\1\0\6\10\1\333"+
    "\47\10\16\0\4\10\1\0\4\10\1\334\51\10\16\0"+
    "\4\10\1\0\31\10\1\335\24\10\16\0\4\10\1\0"+
    "\15\10\1\336\40\10\16\0\4\10\1\0\46\10\1\337"+
    "\7\10\16\0\3\10\1\340\1\0\56\10\16\0\4\10"+
    "\1\0\11\10\1\341\44\10\16\0\4\10\1\0\35\10"+
    "\1\342\20\10\16\0\4\10\1\0\21\10\1\343\34\10"+
    "\16\0\4\10\1\0\50\10\1\344\5\10\16\0\3\10"+
    "\1\345\1\0\56\10\16\0\4\10\1\0\13\10\1\346"+
    "\42\10\16\0\4\10\1\0\13\10\1\347\42\10\16\0"+
    "\4\10\1\0\17\10\1\350\36\10\16\0\4\10\1\0"+
    "\17\10\1\347\36\10\16\0\4\10\1\0\1\10\1\351"+
    "\54\10\16\0\4\10\1\0\23\10\1\352\32\10\16\0"+
    "\4\10\1\0\6\10\1\353\47\10\16\0\4\10\1\0"+
    "\25\10\1\354\30\10\16\0\4\10\1\0\27\10\1\355"+
    "\26\10\16\0\4\10\1\0\33\10\1\355\22\10\16\0"+
    "\4\10\1\0\4\10\1\356\51\10\16\0\4\10\1\0"+
    "\1\10\1\357\54\10\16\0\4\10\1\0\11\10\1\356"+
    "\44\10\16\0\4\10\1\0\6\10\1\357\47\10\16\0"+
    "\4\10\1\0\54\10\1\360\1\10\16\0\4\10\1\0"+
    "\1\10\1\361\54\10\16\0\4\10\1\0\55\10\1\362"+
    "\16\0\4\10\1\0\6\10\1\363\47\10\16\0\4\10"+
    "\1\0\1\10\1\364\54\10\16\0\4\10\1\0\13\10"+
    "\1\365\42\10\16\0\4\10\1\0\31\10\1\366\24\10"+
    "\16\0\4\10\1\0\31\10\1\367\24\10\16\0\4\10"+
    "\1\0\36\10\1\370\17\10\16\0\4\10\1\0\6\10"+
    "\1\364\47\10\16\0\4\10\1\0\17\10\1\371\36\10"+
    "\16\0\4\10\1\0\35\10\1\372\20\10\16\0\4\10"+
    "\1\0\35\10\1\373\20\10\16\0\4\10\1\0\40\10"+
    "\1\374\15\10\16\0\4\10\1\0\4\10\1\375\51\10"+
    "\16\0\4\10\1\0\11\10\1\375\44\10\16\0\4\10"+
    "\1\0\1\376\55\10\16\0\4\10\1\0\31\10\1\377"+
    "\24\10\16\0\4\10\1\0\5\10\1\376\50\10\16\0"+
    "\4\10\1\0\35\10\1\u0100\20\10\16\0\4\10\1\0"+
    "\37\10\1\u0101\16\10\16\0\4\10\1\0\37\10\1\u0102"+
    "\16\10\16\0\4\10\1\0\41\10\1\u0101\14\10\16\0"+
    "\4\10\1\0\41\10\1\u0103\14\10\16\0\4\10\1\0"+
    "\47\10\1\u0104\6\10\16\0\4\10\1\0\2\10\1\u0105"+
    "\53\10\16\0\4\10\1\0\1\u0106\55\10\16\0\4\10"+
    "\1\0\37\10\1\u0107\16\10\16\0\4\10\1\0\51\10"+
    "\1\u0104\4\10\16\0\4\10\1\0\7\10\1\u0105\46\10"+
    "\16\0\4\10\1\0\5\10\1\u0108\50\10\16\0\4\10"+
    "\1\0\41\10\1\u0109\14\10\16\0\4\10\1\0\13\10"+
    "\1\u010a\42\10\16\0\4\10\1\0\17\10\1\u010a\36\10"+
    "\16\0\4\10\1\0\3\10\1\u010b\52\10\16\0\4\10"+
    "\1\0\10\10\1\u010c\45\10\16\0\4\10\1\0\1\10"+
    "\1\u010d\54\10\16\0\4\10\1\0\3\10\1\u010e\52\10"+
    "\16\0\4\10\1\0\6\10\1\u010d\47\10\16\0\4\10"+
    "\1\0\10\10\1\u010f\45\10\16\0\4\10\1\0\1\10"+
    "\1\u0110\54\10\16\0\4\10\1\0\6\10\1\u0111\47\10"+
    "\16\0\4\10\1\0\13\10\1\u0112\42\10\16\0\4\10"+
    "\1\0\17\10\1\u0113\36\10\16\0\4\10\1\0\1\u0114"+
    "\55\10\16\0\4\10\1\0\5\10\1\u0114\50\10\16\0"+
    "\4\10\1\0\1\10\1\u0115\54\10\16\0\4\10\1\0"+
    "\6\10\1\u0116\47\10\16\0\4\10\1\0\15\10\1\u0117"+
    "\40\10\16\0\4\10\1\0\21\10\1\u0118\34\10\16\0"+
    "\4\10\1\0\1\10\1\u0119\54\10\16\0\4\10\1\0"+
    "\6\10\1\u011a\47\10\16\0\4\10\1\0\37\10\1\u011b"+
    "\16\10\16\0\4\10\1\0\41\10\1\u011c\14\10\16\0"+
    "\4\10\1\0\4\10\1\u011d\51\10\16\0\4\10\1\0"+
    "\11\10\1\u011d\44\10\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15665];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\1\11\44\1\10\11"+
    "\66\1\1\0\1\11\260\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /* Generamos un java_cup.Symbol para guardar el tipo de token encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Caracter ilegal <"+yytext()+">");
          }
        case 51: break;
        case 2: 
          { /* ignora el espacio */
          }
        case 52: break;
        case 3: 
          { System.out.print("ENTERO "); return symbol(sym.ENTERO, Integer.valueOf(yytext()));
          }
        case 53: break;
        case 4: 
          { System.out.print("ID "); return symbol(sym.ID, yytext());
          }
        case 54: break;
        case 5: 
          { System.out.print(". "); return symbol(sym.PUNTO);
          }
        case 55: break;
        case 6: 
          { System.out.print("* "); return symbol(sym.ASTERISCO);
          }
        case 56: break;
        case 7: 
          { System.out.print("= "); return symbol(sym.IGUAL);
          }
        case 57: break;
        case 8: 
          { System.out.print(", "); return symbol(sym.COMA);
          }
        case 58: break;
        case 9: 
          { System.out.print(";\n"); return symbol(sym.PUNTOYCOMA);
          }
        case 59: break;
        case 10: 
          { System.out.print("( "); return symbol(sym.PAR_A);
          }
        case 60: break;
        case 11: 
          { System.out.print(") "); return symbol(sym.PAR_C);
          }
        case 61: break;
        case 12: 
          { System.out.print("> "); return symbol(sym.MAYOR);
          }
        case 62: break;
        case 13: 
          { System.out.print("< "); return symbol(sym.MENOR);
          }
        case 63: break;
        case 14: 
          { System.out.print("NUREAL "); return symbol(sym.NUREAL, Float.valueOf(yytext()));
          }
        case 64: break;
        case 15: 
          { System.out.print("OR "); 
                            return symbol(sym.OR);
          }
        case 65: break;
        case 16: 
          { System.out.print("ON "); return symbol(sym.ON);
          }
        case 66: break;
        case 17: 
          { System.out.print("AS "); return symbol(sym.AS);
          }
        case 67: break;
        case 18: 
          { System.out.print("BY "); return symbol(sym.BY);
          }
        case 68: break;
        case 19: 
          { System.out.print("LITERAL_STR ");
                            return symbol(sym.LITERAL_STR, yytext());
          }
        case 69: break;
        case 20: 
          { System.out.print("SET "); 
                            return symbol(sym.SET);
          }
        case 70: break;
        case 21: 
          { System.out.print("USE "); return symbol(sym.USE);
          }
        case 71: break;
        case 22: 
          { System.out.print("ASC "); return symbol(sym.ASC);
          }
        case 72: break;
        case 23: 
          { System.out.print("AND "); 
                            return symbol(sym.AND);
          }
        case 73: break;
        case 24: 
          { System.out.print("TIPO_INT "); return symbol(sym.INT);
          }
        case 74: break;
        case 25: 
          { System.out.print("NOT "); return symbol(sym.NOT);
          }
        case 75: break;
        case 26: 
          { System.out.print("KEY "); return symbol(sym.KEY);
          }
        case 76: break;
        case 27: 
          { System.out.print("FROM "); 
                            return symbol(sym.FROM);
          }
        case 77: break;
        case 28: 
          { System.out.print("DESC "); return symbol(sym.DESC);
          }
        case 78: break;
        case 29: 
          { System.out.print("INTO "); return symbol(sym.INTO);
          }
        case 79: break;
        case 30: 
          { System.out.print("NULL "); return symbol(sym.NULL);
          }
        case 80: break;
        case 31: 
          { System.out.print("JOIN "); 
                            return symbol(sym.JOIN);
          }
        case 81: break;
        case 32: 
          { System.out.print("COUNT "); 
                            return symbol(sym.COUNT);
          }
        case 82: break;
        case 33: 
          { System.out.print("TABLE "); return symbol(sym.TABLE);
          }
        case 83: break;
        case 34: 
          { System.out.print("TIPO_FLOAT "); return symbol(sym.FLOAT);
          }
        case 84: break;
        case 35: 
          { System.out.print("ORDER "); return symbol(sym.ORDER);
          }
        case 85: break;
        case 36: 
          { System.out.print("WHERE "); 
                            return symbol(sym.WHERE);
          }
        case 86: break;
        case 37: 
          { System.out.print("INNER "); 
                            return symbol(sym.INNER);
          }
        case 87: break;
        case 38: 
          { System.out.print("GROUP "); return symbol(sym.GROUP);
          }
        case 88: break;
        case 39: 
          { System.out.print("SELECT "); 
                            return symbol(sym.SELECT);
          }
        case 89: break;
        case 40: 
          { System.out.print("CREATE "); return symbol(sym.CREATE);
          }
        case 90: break;
        case 41: 
          { System.out.print("UPDATE "); 
                                return symbol(sym.UPDATE);
          }
        case 91: break;
        case 42: 
          { System.out.print("INSERT "); return symbol(sym.INSERT);
          }
        case 92: break;
        case 43: 
          { System.out.print("VALUES "); return symbol(sym.VALUES);
          }
        case 93: break;
        case 44: 
          { System.out.print("FOREIGN "); return symbol(sym.FOREIGN);
          }
        case 94: break;
        case 45: 
          { System.out.print("PRIMARY "); return symbol(sym.PRIMARY);
          }
        case 95: break;
        case 46: 
          { System.out.print("DECIMAL "); return symbol(sym.DECIMAL);
          }
        case 96: break;
        case 47: 
          { System.out.print("TIPO_VARCHAR "); return symbol(sym.VARCHAR);
          }
        case 97: break;
        case 48: 
          { System.out.print("DATABASE "); return symbol(sym.DATABASE);
          }
        case 98: break;
        case 49: 
          { System.out.print("REFERENCES "); return symbol(sym.REFERENCES);
          }
        case 99: break;
        case 50: 
          { System.out.print("AUTO_INCREMENT "); return symbol(sym.AUTO_INCREMENT);
          }
        case 100: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
