/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

/* --------------------------Codigo de Usuario----------------------- */
package ejemplocup;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\6\0\1\75"+
    "\1\71\1\72\1\65\1\0\1\67\1\0\1\10\1\0\1\4\11\5"+
    "\1\0\1\70\1\74\1\66\1\73\2\0\1\42\1\55\1\14\1\41"+
    "\1\12\1\23\1\6\1\34\1\47\1\53\1\63\1\13\1\26\1\50"+
    "\1\25\1\40\1\6\1\24\1\11\1\15\1\37\1\61\1\33\1\6"+
    "\1\56\1\6\4\0\1\7\1\0\1\46\1\57\1\21\1\45\1\17"+
    "\1\27\1\6\1\36\1\51\1\54\1\64\1\20\1\32\1\52\1\31"+
    "\1\44\1\6\1\30\1\16\1\22\1\43\1\62\1\35\1\6\1\60"+
    "\1\6\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\36\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\1"+
    "\1\16\10\4\1\17\24\4\1\20\4\4\1\0\1\21"+
    "\1\4\1\22\13\4\1\23\4\4\1\24\4\4\1\25"+
    "\6\4\1\26\6\4\1\27\6\4\1\30\6\4\1\31"+
    "\4\4\1\32\2\4\1\33\1\34\6\4\1\35\2\4"+
    "\1\36\1\37\1\40\6\4\1\41\2\4\1\42\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\76\0\272\0\370\0\u0136\0\76"+
    "\0\u0174\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326"+
    "\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516"+
    "\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706"+
    "\0\u0744\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\u08b8\0\u08f6"+
    "\0\u0934\0\u0972\0\u09b0\0\u09ee\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6"+
    "\0\u0136\0\u0b24\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98"+
    "\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88"+
    "\0\u0ec6\0\u0f04\0\u0f42\0\u0f80\0\u0fbe\0\u0136\0\u0ffc\0\u103a"+
    "\0\u1078\0\u10b6\0\u08b8\0\u08b8\0\u10f4\0\u0136\0\u1132\0\u1170"+
    "\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360"+
    "\0\u139e\0\u0136\0\u13dc\0\u141a\0\u1458\0\u1496\0\u0136\0\u14d4"+
    "\0\u1512\0\u1550\0\u158e\0\u0136\0\u15cc\0\u160a\0\u1648\0\u1686"+
    "\0\u16c4\0\u1702\0\u0136\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838"+
    "\0\u1876\0\u0136\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea"+
    "\0\u0136\0\u1a28\0\u1a66\0\u1aa4\0\u1ae2\0\u1b20\0\u1b5e\0\u0136"+
    "\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\u0136\0\u1c94\0\u1cd2\0\u0136"+
    "\0\u0136\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca\0\u1e08\0\u1e46\0\u0136"+
    "\0\u1e84\0\u1ec2\0\u0136\0\u0136\0\u0136\0\u1f00\0\u1f3e\0\u1f7c"+
    "\0\u1fba\0\u1ff8\0\u2036\0\u0136\0\u2074\0\u20b2\0\u0136\0\u0136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\11\2\7\1\12\1\13\1\14\2\7\1\15\1\16"+
    "\1\17\1\7\1\20\1\7\1\21\1\7\1\22\1\7"+
    "\1\23\1\7\1\24\1\7\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\7\1\36\1\7"+
    "\1\37\1\40\1\41\1\7\1\42\1\7\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\100\0\1\4\103\0\1\60\71\0"+
    "\2\6\2\0\1\60\71\0\4\7\1\0\54\7\15\0"+
    "\4\7\1\0\1\7\1\61\52\7\15\0\4\7\1\0"+
    "\13\7\1\62\40\7\15\0\4\7\1\0\31\7\1\63"+
    "\22\7\15\0\4\7\1\0\6\7\1\64\45\7\15\0"+
    "\4\7\1\0\17\7\1\65\34\7\15\0\4\7\1\0"+
    "\35\7\1\66\16\7\15\0\4\7\1\0\13\7\1\67"+
    "\40\7\15\0\4\7\1\0\13\7\1\70\23\7\1\71"+
    "\14\7\15\0\4\7\1\0\17\7\1\72\34\7\15\0"+
    "\4\7\1\0\17\7\1\73\21\7\1\71\12\7\15\0"+
    "\4\7\1\0\23\7\1\74\30\7\15\0\4\7\1\0"+
    "\25\7\1\75\26\7\15\0\4\7\1\0\1\76\26\7"+
    "\1\77\24\7\15\0\4\7\1\0\13\7\1\100\40\7"+
    "\15\0\4\7\1\0\1\7\1\101\27\7\1\102\22\7"+
    "\15\0\4\7\1\0\1\103\53\7\15\0\4\7\1\0"+
    "\5\7\1\104\25\7\1\105\20\7\15\0\4\7\1\0"+
    "\17\7\1\106\34\7\15\0\4\7\1\0\6\7\1\107"+
    "\26\7\1\110\16\7\15\0\4\7\1\0\5\7\1\111"+
    "\46\7\15\0\4\7\1\0\37\7\1\112\14\7\15\0"+
    "\4\7\1\0\41\7\1\113\12\7\15\0\4\7\1\0"+
    "\14\7\1\114\37\7\15\0\4\7\1\0\20\7\1\115"+
    "\33\7\15\0\4\7\1\0\45\7\1\116\6\7\15\0"+
    "\4\7\1\0\47\7\1\116\4\7\15\0\4\7\1\0"+
    "\31\7\1\117\22\7\15\0\4\7\1\0\35\7\1\120"+
    "\16\7\15\0\4\7\1\0\1\7\1\121\52\7\15\0"+
    "\4\7\1\0\6\7\1\122\45\7\11\0\75\123\1\124"+
    "\4\0\2\60\74\0\4\7\1\0\2\7\1\125\1\7"+
    "\1\126\47\7\15\0\4\7\1\0\1\7\1\127\52\7"+
    "\15\0\4\7\1\0\44\7\1\130\7\7\15\0\4\7"+
    "\1\0\7\7\1\131\1\7\1\126\42\7\15\0\4\7"+
    "\1\0\6\7\1\132\45\7\15\0\4\7\1\0\46\7"+
    "\1\133\5\7\15\0\4\7\1\0\14\7\1\134\37\7"+
    "\15\0\4\7\1\0\30\7\1\135\23\7\15\0\4\7"+
    "\1\0\20\7\1\136\33\7\15\0\4\7\1\0\34\7"+
    "\1\137\17\7\15\0\4\7\1\0\1\7\1\140\52\7"+
    "\15\0\4\7\1\0\6\7\1\141\45\7\15\0\4\7"+
    "\1\0\1\7\1\142\52\7\15\0\4\7\1\0\30\7"+
    "\1\143\23\7\15\0\4\7\1\0\36\7\1\144\15\7"+
    "\15\0\4\7\1\0\1\145\53\7\15\0\4\7\1\0"+
    "\4\7\1\146\47\7\15\0\4\7\1\0\3\7\1\147"+
    "\50\7\15\0\4\7\1\0\6\7\1\142\45\7\15\0"+
    "\4\7\1\0\34\7\1\150\17\7\15\0\4\7\1\0"+
    "\40\7\1\151\13\7\15\0\4\7\1\0\5\7\1\152"+
    "\46\7\15\0\4\7\1\0\11\7\1\153\42\7\15\0"+
    "\4\7\1\0\10\7\1\147\43\7\15\0\4\7\1\0"+
    "\4\7\1\154\32\7\1\155\14\7\15\0\4\7\1\0"+
    "\11\7\1\154\27\7\1\156\12\7\15\0\4\7\1\0"+
    "\36\7\1\157\15\7\15\0\4\7\1\0\40\7\1\160"+
    "\13\7\15\0\4\7\1\0\13\7\1\161\40\7\15\0"+
    "\4\7\1\0\17\7\1\162\34\7\15\0\4\7\1\0"+
    "\45\7\1\163\6\7\15\0\4\7\1\0\47\7\1\163"+
    "\4\7\15\0\4\7\1\0\1\7\1\164\52\7\15\0"+
    "\4\7\1\0\31\7\1\165\22\7\15\0\4\7\1\0"+
    "\2\7\1\166\51\7\15\0\4\7\1\0\6\7\1\167"+
    "\45\7\15\0\4\7\1\0\35\7\1\170\16\7\15\0"+
    "\4\7\1\0\7\7\1\171\44\7\15\0\4\7\1\0"+
    "\15\7\1\172\36\7\15\0\4\7\1\0\1\7\1\173"+
    "\52\7\15\0\4\7\1\0\21\7\1\172\32\7\15\0"+
    "\4\7\1\0\6\7\1\174\45\7\15\0\4\7\1\0"+
    "\13\7\1\175\40\7\15\0\4\7\1\0\17\7\1\176"+
    "\34\7\15\0\4\7\1\0\31\7\1\177\22\7\15\0"+
    "\4\7\1\0\15\7\1\200\36\7\15\0\4\7\1\0"+
    "\3\7\1\201\50\7\15\0\4\7\1\0\31\7\1\202"+
    "\22\7\15\0\4\7\1\0\35\7\1\203\16\7\15\0"+
    "\4\7\1\0\21\7\1\204\32\7\15\0\4\7\1\0"+
    "\10\7\1\201\43\7\15\0\4\7\1\0\35\7\1\205"+
    "\16\7\15\0\4\7\1\0\1\7\1\206\52\7\15\0"+
    "\4\7\1\0\6\7\1\207\45\7\15\0\4\7\1\0"+
    "\37\7\1\210\14\7\15\0\4\7\1\0\41\7\1\210"+
    "\12\7\15\0\4\7\1\0\3\7\1\211\50\7\15\0"+
    "\4\7\1\0\10\7\1\212\43\7\15\0\4\7\1\0"+
    "\3\7\1\213\50\7\15\0\4\7\1\0\4\7\1\214"+
    "\47\7\15\0\4\7\1\0\1\7\1\215\52\7\15\0"+
    "\4\7\1\0\10\7\1\216\43\7\15\0\4\7\1\0"+
    "\11\7\1\217\42\7\15\0\4\7\1\0\6\7\1\215"+
    "\45\7\15\0\4\7\1\0\13\7\1\220\40\7\15\0"+
    "\4\7\1\0\17\7\1\220\34\7\15\0\4\7\1\0"+
    "\1\7\1\221\52\7\15\0\4\7\1\0\6\7\1\221"+
    "\45\7\15\0\4\7\1\0\4\7\1\222\47\7\15\0"+
    "\4\7\1\0\31\7\1\223\22\7\15\0\4\7\1\0"+
    "\44\7\1\224\7\7\15\0\4\7\1\0\11\7\1\225"+
    "\42\7\15\0\4\7\1\0\35\7\1\226\16\7\15\0"+
    "\4\7\1\0\46\7\1\227\5\7\15\0\4\7\1\0"+
    "\13\7\1\230\40\7\15\0\4\7\1\0\17\7\1\230"+
    "\34\7\15\0\4\7\1\0\23\7\1\231\30\7\15\0"+
    "\4\7\1\0\25\7\1\232\26\7\15\0\4\7\1\0"+
    "\4\7\1\233\47\7\15\0\4\7\1\0\1\7\1\234"+
    "\52\7\15\0\4\7\1\0\11\7\1\233\42\7\15\0"+
    "\4\7\1\0\6\7\1\234\45\7\15\0\4\7\1\0"+
    "\1\7\1\235\52\7\15\0\4\7\1\0\13\7\1\236"+
    "\40\7\15\0\4\7\1\0\31\7\1\237\22\7\15\0"+
    "\4\7\1\0\6\7\1\235\45\7\15\0\4\7\1\0"+
    "\17\7\1\240\34\7\15\0\4\7\1\0\35\7\1\241"+
    "\16\7\15\0\4\7\1\0\31\7\1\242\22\7\15\0"+
    "\4\7\1\0\35\7\1\243\16\7\15\0\4\7\1\0"+
    "\45\7\1\244\6\7\15\0\4\7\1\0\1\245\53\7"+
    "\15\0\4\7\1\0\47\7\1\244\4\7\15\0\4\7"+
    "\1\0\5\7\1\246\46\7\15\0\4\7\1\0\13\7"+
    "\1\247\40\7\15\0\4\7\1\0\17\7\1\247\34\7"+
    "\15\0\4\7\1\0\1\7\1\250\52\7\15\0\4\7"+
    "\1\0\6\7\1\250\45\7\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8432];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\1\11\36\1\10\11"+
    "\44\1\1\0\125\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /* Generamos un java_cup.Symbol para guardar el tipo de token encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Caracter ilegal <"+yytext()+">");
          }
        case 36: break;
        case 2: 
          { /* ignora el espacio */
          }
        case 37: break;
        case 3: 
          { System.out.print("ENTERO ");
                            return symbol(sym.ENTERO, Integer.valueOf(yytext()));
          }
        case 38: break;
        case 4: 
          { System.out.print("ID ");
                             return symbol(sym.ID, yytext());
          }
        case 39: break;
        case 5: 
          { System.out.print(". ");
                             return symbol(sym.PUNTO);
          }
        case 40: break;
        case 6: 
          { System.out.print("* ");
                             return symbol(sym.ASTERISCO);
          }
        case 41: break;
        case 7: 
          { System.out.print("= ");
                            return symbol(sym.IGUAL);
          }
        case 42: break;
        case 8: 
          { System.out.print(", ");
                             return symbol(sym.COMA);
          }
        case 43: break;
        case 9: 
          { System.out.print("; ");
                            return symbol(sym.PUNTOYCOMA);
          }
        case 44: break;
        case 10: 
          { System.out.print("( ");
                             return symbol(sym.PAR_A);
          }
        case 45: break;
        case 11: 
          { System.out.print(") ");
                            return symbol(sym.PAR_C);
          }
        case 46: break;
        case 12: 
          { System.out.print("> ");
                            return symbol(sym.MAYOR);
          }
        case 47: break;
        case 13: 
          { System.out.print("< ");
                             return symbol(sym.MENOR);
          }
        case 48: break;
        case 14: 
          { System.out.print("NUREAL ");
                             return symbol(sym.NUREAL, Float.valueOf(yytext()));
          }
        case 49: break;
        case 15: 
          { System.out.print("ON ");
                            return symbol(sym.ON);
          }
        case 50: break;
        case 16: 
          { System.out.print("BY ");
                              return symbol(sym.BY);
          }
        case 51: break;
        case 17: 
          { System.out.print("LITERAL_STR ");
                            return symbol(sym.LITERAL_STR, yytext());
          }
        case 52: break;
        case 18: 
          { System.out.print("SET ");
                             return symbol(sym.SET);
          }
        case 53: break;
        case 19: 
          { System.out.print("USE ");
                            return symbol(sym.USE);
          }
        case 54: break;
        case 20: 
          { System.out.print("ASC ");
                             return symbol(sym.ASC);
          }
        case 55: break;
        case 21: 
          { System.out.print("TIPO_INT "); 
        return symbol(sym.INT);
          }
        case 56: break;
        case 22: 
          { System.out.print("KEY "); 
     return symbol(sym.KEY);
          }
        case 57: break;
        case 23: 
          { System.out.print("FROM ");
                              return symbol(sym.FROM);
          }
        case 58: break;
        case 24: 
          { System.out.print("DESC ");
                            return symbol(sym.DESC);
          }
        case 59: break;
        case 25: 
          { System.out.print("JOIN ");
                              return symbol(sym.JOIN);
          }
        case 60: break;
        case 26: 
          { System.out.print("TABLE ");
                           return symbol(sym.TABLE);
          }
        case 61: break;
        case 27: 
          { System.out.print("ORDER ");
                             return symbol(sym.ORDER);
          }
        case 62: break;
        case 28: 
          { System.out.print("WHERE ");
                           return symbol(sym.WHERE);
          }
        case 63: break;
        case 29: 
          { System.out.print("INNER ");
                              return symbol(sym.INNER);
          }
        case 64: break;
        case 30: 
          { System.out.print("SELECT ");
                          return symbol(sym.SELECT);
          }
        case 65: break;
        case 31: 
          { System.out.print("CREATE ");
                              return symbol(sym.CREATE);
          }
        case 66: break;
        case 32: 
          { System.out.print("UPDATE ");
                              return symbol(sym.UPDATE);
          }
        case 67: break;
        case 33: 
          { System.out.print("PRIMARY "); 
        return symbol(sym.PRIMARY);
          }
        case 68: break;
        case 34: 
          { System.out.print("TIPO_VARCHAR "); 
    return symbol(sym.VARCHAR);
          }
        case 69: break;
        case 35: 
          { System.out.print("DATABASE ");
                             return symbol(sym.DATABASE);
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
