
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 09 16:25:40 CST 2026
//----------------------------------------------------

package ejemplocup;

import java_cup.runtime.*;
import java.io.FileReader;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Jun 09 16:25:40 CST 2026
  */
public class AnalizadorSemantico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSemantico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSemantico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSemantico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\004\012\000\002\004\007" +
    "\000\002\004\005\000\002\004\004\000\002\004\010\000" +
    "\002\004\014\000\002\004\011\000\002\024\005\000\002" +
    "\024\003\000\002\025\003\000\002\023\003\000\002\023" +
    "\003\000\002\027\005\000\002\027\003\000\002\030\003" +
    "\000\002\030\005\000\002\030\007\000\002\030\006\000" +
    "\002\030\010\000\002\007\005\000\002\007\003\000\002" +
    "\020\005\000\002\020\003\000\002\033\005\000\002\033" +
    "\003\000\002\034\005\000\002\031\003\000\002\031\003" +
    "\000\002\021\004\000\002\021\006\000\002\021\007\000" +
    "\002\021\006\000\002\021\005\000\002\032\014\000\002" +
    "\022\003\000\002\022\006\000\002\022\003\000\002\022" +
    "\010\000\002\022\010\000\002\012\011\000\002\012\002" +
    "\000\002\005\004\000\002\005\002\000\002\035\005\000" +
    "\002\035\005\000\002\035\003\000\002\036\005\000\002" +
    "\036\005\000\002\036\003\000\002\026\005\000\002\026" +
    "\002\000\002\016\003\000\002\016\003\000\002\016\003" +
    "\000\002\013\005\000\002\013\002\000\002\014\005\000" +
    "\002\014\003\000\002\015\003\000\002\015\004\000\002" +
    "\015\004\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\010\003\000\002\011\003" +
    "\000\002\011\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\014\004\013\007\011\023\005\027\004\032" +
    "\010\001\002\000\006\030\162\031\163\001\002\000\004" +
    "\024\141\001\002\000\004\014\140\001\002\000\016\002" +
    "\uffff\004\uffff\007\uffff\023\uffff\027\uffff\032\uffff\001\002" +
    "\000\004\062\137\001\002\000\004\062\036\001\002\000" +
    "\016\002\124\004\013\007\011\023\005\027\004\032\010" +
    "\001\002\000\010\011\016\055\020\062\014\001\002\000" +
    "\044\005\uffbb\006\uffbb\011\uffbb\012\uffbb\013\uffbb\014\uffbb" +
    "\016\uffbb\022\121\033\uffbb\035\uffbb\036\uffbb\037\uffbb\040" +
    "\uffbb\053\uffbb\054\uffbb\056\uffbb\057\uffbb\001\002\000\006" +
    "\005\ufff0\013\ufff0\001\002\000\004\005\ufff3\001\002\000" +
    "\006\005\ufff2\013\117\001\002\000\004\015\112\001\002" +
    "\000\004\005\035\001\002\000\012\005\uffef\011\023\013" +
    "\uffef\053\024\001\002\000\012\060\032\061\031\062\026" +
    "\063\027\001\002\000\004\062\025\001\002\000\006\005" +
    "\uffee\013\uffee\001\002\000\024\006\uffbd\013\uffbd\014\uffbd" +
    "\016\uffbd\033\uffbd\053\uffbd\054\uffbd\056\uffbd\057\uffbd\001" +
    "\002\000\024\006\uffbe\013\uffbe\014\uffbe\016\uffbe\033\uffbe" +
    "\053\uffbe\054\uffbe\056\uffbe\057\uffbe\001\002\000\004\053" +
    "\033\001\002\000\024\006\uffbf\013\uffbf\014\uffbf\016\uffbf" +
    "\033\uffbf\053\uffbf\054\uffbf\056\uffbf\057\uffbf\001\002\000" +
    "\024\006\uffc0\013\uffc0\014\uffc0\016\uffc0\033\uffc0\053\uffc0" +
    "\054\uffc0\056\uffc0\057\uffc0\001\002\000\004\062\034\001" +
    "\002\000\006\005\uffed\013\uffed\001\002\000\004\062\036" +
    "\001\002\000\024\006\uffbc\010\uffbc\014\uffbc\015\uffbc\017" +
    "\uffbc\021\uffbc\025\uffbc\033\uffbc\054\uffbc\001\002\000\014" +
    "\006\uffd5\014\uffd5\017\040\033\uffd5\054\uffd5\001\002\000" +
    "\004\020\104\001\002\000\012\006\042\014\uffd3\033\uffd3" +
    "\054\uffd3\001\002\000\006\015\065\062\014\001\002\000" +
    "\010\014\uffcb\033\uffcb\054\045\001\002\000\006\014\uffc6" +
    "\033\053\001\002\000\004\034\046\001\002\000\004\062" +
    "\014\001\002\000\010\013\051\014\uffcc\033\uffcc\001\002" +
    "\000\012\013\uffe9\014\uffe9\016\uffe9\033\uffe9\001\002\000" +
    "\004\062\014\001\002\000\012\013\uffea\014\uffea\016\uffea" +
    "\033\uffea\001\002\000\004\034\055\001\002\000\004\014" +
    "\ufffd\001\002\000\004\062\014\001\002\000\006\013\uffc4" +
    "\014\uffc4\001\002\000\006\013\063\014\uffc7\001\002\000" +
    "\012\013\uffc3\014\uffc3\035\061\036\062\001\002\000\006" +
    "\013\uffc2\014\uffc2\001\002\000\006\013\uffc1\014\uffc1\001" +
    "\002\000\004\062\014\001\002\000\006\013\uffc5\014\uffc5" +
    "\001\002\000\006\015\065\062\014\001\002\000\014\014" +
    "\uffd4\033\uffd4\054\uffd4\056\076\057\077\001\002\000\016" +
    "\014\uffd0\016\uffd0\033\uffd0\054\uffd0\056\uffd0\057\uffd0\001" +
    "\002\000\024\012\071\014\uffcd\016\uffcd\033\uffcd\037\073" +
    "\040\072\054\uffcd\056\uffcd\057\uffcd\001\002\000\012\060" +
    "\uffca\061\uffca\062\uffca\063\uffca\001\002\000\012\060\uffc8" +
    "\061\uffc8\062\uffc8\063\uffc8\001\002\000\012\060\uffc9\061" +
    "\uffc9\062\uffc9\063\uffc9\001\002\000\012\060\032\061\031" +
    "\062\026\063\027\001\002\000\016\014\uffcf\016\uffcf\033" +
    "\uffcf\054\uffcf\056\uffcf\057\uffcf\001\002\000\006\015\065" +
    "\062\014\001\002\000\006\015\065\062\014\001\002\000" +
    "\016\014\uffd1\016\uffd1\033\uffd1\054\uffd1\056\uffd1\057\uffd1" +
    "\001\002\000\016\014\uffd2\016\uffd2\033\uffd2\054\uffd2\056" +
    "\uffd2\057\uffd2\001\002\000\010\016\103\056\076\057\077" +
    "\001\002\000\016\014\uffce\016\uffce\033\uffce\054\uffce\056" +
    "\uffce\057\uffce\001\002\000\004\062\036\001\002\000\004" +
    "\021\106\001\002\000\004\062\014\001\002\000\004\012" +
    "\110\001\002\000\004\062\014\001\002\000\012\006\uffd6" +
    "\014\uffd6\033\uffd6\054\uffd6\001\002\000\004\011\113\001" +
    "\002\000\004\016\114\001\002\000\010\005\uffec\013\uffec" +
    "\053\115\001\002\000\004\062\116\001\002\000\006\005" +
    "\uffeb\013\uffeb\001\002\000\006\055\020\062\014\001\002" +
    "\000\006\005\ufff1\013\ufff1\001\002\000\004\062\122\001" +
    "\002\000\042\005\uffba\006\uffba\011\uffba\012\uffba\013\uffba" +
    "\014\uffba\016\uffba\033\uffba\035\uffba\036\uffba\037\uffba\040" +
    "\uffba\053\uffba\054\uffba\056\uffba\057\uffba\001\002\000\016" +
    "\002\001\004\001\007\001\023\001\027\001\032\001\001" +
    "\002\000\004\002\000\001\002\000\004\010\126\001\002" +
    "\000\004\062\014\001\002\000\010\006\042\013\134\014" +
    "\uffd3\001\002\000\010\006\uffe5\013\uffe5\014\uffe5\001\002" +
    "\000\004\012\132\001\002\000\012\060\032\061\031\062" +
    "\026\063\027\001\002\000\010\006\uffe4\013\uffe4\014\uffe4" +
    "\001\002\000\004\062\014\001\002\000\004\014\ufffc\001" +
    "\002\000\010\006\uffe6\013\uffe6\014\uffe6\001\002\000\004" +
    "\014\ufffa\001\002\000\016\002\ufffe\004\ufffe\007\ufffe\023" +
    "\ufffe\027\ufffe\032\ufffe\001\002\000\004\062\036\001\002" +
    "\000\006\015\144\025\143\001\002\000\004\015\157\001" +
    "\002\000\004\062\014\001\002\000\006\013\051\016\146" +
    "\001\002\000\004\025\147\001\002\000\004\015\150\001" +
    "\002\000\012\060\032\061\031\062\026\063\027\001\002" +
    "\000\006\013\154\016\155\001\002\000\006\013\ufff4\016" +
    "\ufff4\001\002\000\006\013\ufff5\016\ufff5\001\002\000\012" +
    "\060\032\061\031\062\026\063\027\001\002\000\004\014" +
    "\ufff8\001\002\000\006\013\ufff6\016\ufff6\001\002\000\012" +
    "\060\032\061\031\062\026\063\027\001\002\000\006\013" +
    "\154\016\161\001\002\000\004\014\ufff7\001\002\000\004" +
    "\062\240\001\002\000\004\062\036\001\002\000\004\015" +
    "\165\001\002\000\006\051\171\062\170\001\002\000\006" +
    "\013\uffe7\016\uffe7\001\002\000\006\013\uffe3\016\uffe3\001" +
    "\002\000\012\026\213\041\214\042\211\050\212\001\002" +
    "\000\004\044\177\001\002\000\006\013\uffe2\016\uffe2\001" +
    "\002\000\006\013\174\016\175\001\002\000\006\051\171" +
    "\062\170\001\002\000\004\014\ufff9\001\002\000\006\013" +
    "\uffe8\016\uffe8\001\002\000\004\015\200\001\002\000\004" +
    "\062\201\001\002\000\004\016\202\001\002\000\004\052" +
    "\203\001\002\000\004\062\204\001\002\000\004\015\205" +
    "\001\002\000\004\062\206\001\002\000\004\016\207\001" +
    "\002\000\006\013\uffdc\016\uffdc\001\002\000\014\013\uffe1" +
    "\016\uffe1\043\232\045\234\046\233\001\002\000\004\015" +
    "\227\001\002\000\004\015\222\001\002\000\016\013\uffd9" +
    "\015\215\016\uffd9\043\uffd9\045\uffd9\046\uffd9\001\002\000" +
    "\014\013\uffdb\016\uffdb\043\uffdb\045\uffdb\046\uffdb\001\002" +
    "\000\004\060\216\001\002\000\004\013\217\001\002\000" +
    "\004\060\220\001\002\000\004\016\221\001\002\000\014" +
    "\013\uffd8\016\uffd8\043\uffd8\045\uffd8\046\uffd8\001\002\000" +
    "\004\060\223\001\002\000\004\013\224\001\002\000\004" +
    "\060\225\001\002\000\004\016\226\001\002\000\014\013" +
    "\uffd7\016\uffd7\043\uffd7\045\uffd7\046\uffd7\001\002\000\004" +
    "\060\230\001\002\000\004\016\231\001\002\000\014\013" +
    "\uffda\016\uffda\043\uffda\045\uffda\046\uffda\001\002\000\004" +
    "\044\236\001\002\000\004\047\235\001\002\000\006\013" +
    "\uffdd\016\uffdd\001\002\000\006\013\uffde\016\uffde\001\002" +
    "\000\010\013\uffe0\016\uffe0\045\237\001\002\000\006\013" +
    "\uffdf\016\uffdf\001\002\000\004\014\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\010\002\011\003\006\004\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\124\001\001\000" +
    "\006\003\122\004\005\001\001\000\012\011\021\023\020" +
    "\027\016\030\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\027\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\036\001\001\000\002\001\001\000\004\012\040\001" +
    "\001\000\002\001\001\000\004\005\042\001\001\000\010" +
    "\011\067\035\065\036\066\001\001\000\004\026\043\001" +
    "\001\000\004\013\053\001\001\000\002\001\001\000\006" +
    "\007\046\011\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\051\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\057\014\056\015" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\011" +
    "\057\015\063\001\001\000\002\001\001\000\010\011\067" +
    "\035\101\036\066\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\074\001\001\000" +
    "\002\001\001\000\006\011\067\036\100\001\001\000\006" +
    "\011\067\036\077\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\104" +
    "\001\001\000\002\001\001\000\004\011\106\001\001\000" +
    "\002\001\001\000\004\011\110\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\011\021\030\117" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\011\130\033\126\034\127\001\001\000\004\005" +
    "\134\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\006\132\001\001\000\002\001\001\000\006\011\130\034" +
    "\135\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\141\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\007\144\011\047" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\006\151\024\150\025\152\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\151\025\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\006\151\024\157\025\152\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\163" +
    "\001\001\000\002\001\001\000\012\020\172\021\166\031" +
    "\165\032\171\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\207\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\021\166\031\175\032\171" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSemantico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSemantico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSemantico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }
   
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    public static void main(String[] args){
        try {
            AnalizadorSemantico asin = new AnalizadorSemantico(
                    new AnalizadorLexico( new FileReader(args[0])));
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados SQL***");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSemantico$actions {
  private final AnalizadorSemantico parser;

  /** Constructor */
  CUP$AnalizadorSemantico$actions(AnalizadorSemantico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSemantico$do_action(
    int                        CUP$AnalizadorSemantico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSemantico$parser,
    java.util.Stack            CUP$AnalizadorSemantico$stack,
    int                        CUP$AnalizadorSemantico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSemantico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSemantico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // nombre_compuesto ::= ID PUNTO ID 
            {
              Object RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id2; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // nombre_compuesto ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // nombre_tabla ::= ID 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = d; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("nombre_tabla",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // valor ::= ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=i; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // valor ::= LITERAL_STR 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=s; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // valor ::= NUREAL 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=n; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // valor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT=e; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // elemento_order ::= nombre_compuesto DESC 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // elemento_order ::= nombre_compuesto ASC 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // elemento_order ::= nombre_compuesto 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_order",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // lista_order ::= elemento_order 
            {
              Object RESULT =null;
		int eoleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object eo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = eo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_order",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // lista_order ::= lista_order COMA elemento_order 
            {
              Object RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int loright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int eoleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object eo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = eo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_order",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // clausula_order ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_order",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // clausula_order ::= ORDER BY lista_order 
            {
              Object RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int loright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lo = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = lo; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_order",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // comparador ::= MENOR 
            {
              Object RESULT =null;
		 RESULT = "<"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // comparador ::= MAYOR 
            {
              Object RESULT =null;
		 RESULT = ">"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // comparador ::= IGUAL 
            {
              Object RESULT =null;
		 RESULT = "="; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // clausula_group ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_group",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // clausula_group ::= GROUP BY lista_campos 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = lc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_group",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // termino_condicion ::= nombre_compuesto 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("termino_condicion",28, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // termino_condicion ::= PAR_A condicion_logica PAR_C 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("termino_condicion",28, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // termino_condicion ::= nombre_compuesto comparador valor 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("termino_condicion",28, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // condicion_logica ::= termino_condicion 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("condicion_logica",27, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // condicion_logica ::= condicion_logica OR termino_condicion 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("condicion_logica",27, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // condicion_logica ::= condicion_logica AND termino_condicion 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("condicion_logica",27, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // clausula_where ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_where",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // clausula_where ::= WHERE condicion_logica 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = c; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_where",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // clausula_join ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_join",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // clausula_join ::= INNER JOIN nombre_tabla ON nombre_compuesto IGUAL nombre_compuesto 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nt; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("clausula_join",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tipo_dato ::= DECIMAL PAR_A ENTERO COMA ENTERO PAR_C 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = "DECIMAL"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // tipo_dato ::= FLOAT PAR_A ENTERO COMA ENTERO PAR_C 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = "FLOAT_DECIMAL"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tipo_dato ::= VARCHAR PAR_A ENTERO PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = "VARCHAR-" + e; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // tipo_dato ::= INT 
            {
              Object RESULT =null;
		 RESULT = "INT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("tipo_dato",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // llave_foranea ::= FOREIGN KEY PAR_A ID PAR_C REFERENCES ID PAR_A ID PAR_C 
            {
              Object RESULT =null;
		int id_fkleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).left;
		int id_fkright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).right;
		String id_fk = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).value;
		int id_refleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int id_refright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		String id_ref = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int id_col_refleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int id_col_refright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		String id_col_ref = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = id_fk + ":" + id_ref + ":" + id_col_ref; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("llave_foranea",24, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-9)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // columna ::= ID tipo_dato AUTO_INCREMENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 RESULT = id + ":" + td + ":false"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // columna ::= ID tipo_dato NOT NULL 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		 RESULT = id + ":" + td + ":false"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // columna ::= ID tipo_dato PRIMARY KEY AUTO_INCREMENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		 RESULT = id + ":" + td + ":true"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // columna ::= ID tipo_dato PRIMARY KEY 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		 RESULT = id + ":" + td + ":true"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // columna ::= ID tipo_dato 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object td = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = id + ":" + td + ":false"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("columna",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // elemento_columna ::= llave_foranea 
            {
              Object RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lf = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = "FK:" + lf; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_columna",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // elemento_columna ::= columna 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = c; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_columna",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // asignacion ::= nombre_compuesto IGUAL valor 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                   Object[] asig = new Object[2];
                   asig[0] = nc;
                   asig[1] = v;
                   RESULT = asig;
               
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("asignacion",26, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_asignaciones ::= asignacion 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                         java.util.List<Object[]> lista = new java.util.ArrayList<>();
                         lista.add((Object[]) a);
                         RESULT = lista;
                     
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_asignaciones",25, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_asignaciones ::= lista_asignaciones COMA asignacion 
            {
              Object RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object la = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                         java.util.List<Object[]> lista = (java.util.List<Object[]>) la;
                         lista.add((Object[]) a);
                         RESULT = lista;
                     
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_asignaciones",25, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_columnas ::= elemento_columna 
            {
              Object RESULT =null;
		int ecleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ecright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ec = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                    java.util.List<String> lista = new java.util.ArrayList<>();
                    lista.add(ec.toString());
                    RESULT = lista;
                
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_columnas",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_columnas ::= lista_columnas COMA elemento_columna 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int ecleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ecright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ec = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                    java.util.List<String> lista = (java.util.List<String>) lc;
                    lista.add(ec.toString());
                    RESULT = lista;
                
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_columnas",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_campos ::= nombre_compuesto 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                   java.util.List<String> lista = new java.util.ArrayList<>();
                   lista.add(nc.toString());
                   RESULT = lista;
               
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_campos ::= lista_campos COMA nombre_compuesto 
            {
              Object RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                   java.util.List<String> lista = (java.util.List<String>) lc;
                   lista.add(nc.toString());
                   RESULT = lista;
               
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // elemento_select ::= COUNT PAR_A ASTERISCO PAR_C AS ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = "COUNT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_select",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // elemento_select ::= COUNT PAR_A ASTERISCO PAR_C 
            {
              Object RESULT =null;
		 RESULT = "COUNT"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_select",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // elemento_select ::= nombre_compuesto ASTERISCO valor AS ID 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_select",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // elemento_select ::= nombre_compuesto AS ID 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_select",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // elemento_select ::= nombre_compuesto 
            {
              Object RESULT =null;
		int ncleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int ncright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object nc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = nc; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_select",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // lista_campos_select ::= elemento_select 
            {
              Object RESULT =null;
		int esleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object es = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                          java.util.List<String> lista = new java.util.ArrayList<>();
                          lista.add(es.toString());
                          RESULT = lista;
                      
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos_select",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_campos_select ::= lista_campos_select COMA elemento_select 
            {
              Object RESULT =null;
		int lcsleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lcsright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lcs = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int esleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object es = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                          java.util.List<String> lista = (java.util.List<String>) lcs;
                          lista.add(es.toString());
                          RESULT = lista;
                      
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_campos_select",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // campos_select ::= lista_campos_select 
            {
              Object RESULT =null;
		int lcsleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int lcsright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object lcs = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = lcs; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("campos_select",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // campos_select ::= ASTERISCO 
            {
              Object RESULT =null;
		 RESULT = "*"; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("campos_select",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // elemento_valor ::= valor 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 RESULT = v; 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("elemento_valor",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_valores ::= elemento_valor 
            {
              Object RESULT =null;
		int evleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int evright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ev = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                    java.util.List<Object> lista = new java.util.ArrayList<>();
                    lista.add(ev);
                    RESULT = lista;
                
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_valores",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_valores ::= lista_valores COMA elemento_valor 
            {
              Object RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int evleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int evright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object ev = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
                    java.util.List<Object> lista = (java.util.List<Object>) lv;
                    lista.add(ev);
                    RESULT = lista;
                
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("lista_valores",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= INSERT INTO nombre_tabla VALUES PAR_A lista_valores PAR_C 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int lvleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 
            VerificadorSemantico.verificarInsert(nt.toString(), null, (java.util.List<Object>)lv);
            RESULT = lv;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= INSERT INTO nombre_tabla PAR_A lista_campos PAR_C VALUES PAR_A lista_valores PAR_C 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)).value;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)).value;
		int lvleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 
            VerificadorSemantico.verificarInsert(nt.toString(), (java.util.List<String>)lc, (java.util.List<Object>)lv);
            RESULT = lv;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-9)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= CREATE TABLE nombre_tabla PAR_A lista_columnas PAR_C 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int lcleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object lc = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		 
            if (VerificadorSemantico.verificarCreateTable(nt.toString())) {
                java.util.List<String> columnas = (java.util.List<String>) lc;
                for(String col : columnas){
                    if(col.startsWith("FK:")) {
                        String[] partes = col.split(":");
                        VerificadorSemantico.verificarLlaveForanea(nt.toString(), partes[1], partes[2], partes[3]);
                    } else {
                        String[] datos = col.split(":"); // Ahora siempre tendrá 3 partes exactas
                        boolean pk = datos[2].equals("true");
                        String tipoReal = datos[1].replace("-", ":"); // Restauramos a VARCHAR:150
                        VerificadorSemantico.registrarColumna(nt.toString(), datos[0], tipoReal, pk);
                    }
                }
            }
            RESULT = lc;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= USE ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
            VerificadorSemantico.registrarUseDatabase(id.toString());
            RESULT = id;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= CREATE DATABASE ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
            VerificadorSemantico.registrarCreateDatabase(id.toString());
            RESULT = id;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= UPDATE nombre_tabla SET lista_asignaciones clausula_where 
            {
              Object RESULT =null;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object la = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
        java.util.List<Object[]> asigns = (java.util.List<Object[]>) la;
        for (Object[] asig : asigns) {
            VerificadorSemantico.verificarUpdate(nt.toString(), asig[0].toString(), asig[1]);
        }
        RESULT = la;
    
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= SELECT campos_select FROM nombre_tabla clausula_join clausula_where clausula_group clausula_order 
            {
              Object RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).right;
		Object cs = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-6)).value;
		int ntleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).left;
		int ntright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).right;
		Object nt = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-4)).value;
		int cjleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).left;
		int cjright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).right;
		Object cj = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-2)).value;
		int cgleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int cgright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object cg = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		int coleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).left;
		int coright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()).right;
		Object co = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.peek()).value;
		 
            VerificadorSemantico.verificarTablaExiste(nt.toString(), "consultar");
            RESULT = cs;
        
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sentencia ::= instruccion PUNTOYCOMA 
            {
              Object RESULT =null;
		 
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= sentencia 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSemantico$parser.done_parsing();
          return CUP$AnalizadorSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // inicio ::= inicio sentencia 
            {
              Object RESULT =null;

              CUP$AnalizadorSemantico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.elementAt(CUP$AnalizadorSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSemantico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSemantico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

