/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

/* --------------------------Codigo de Usuario----------------------- */
package ejemplocup;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\6\0\1\71"+
    "\1\65\1\66\1\61\1\0\1\63\1\0\1\10\1\0\1\4\11\5"+
    "\1\0\1\64\1\70\1\62\1\67\2\0\1\42\1\55\1\14\1\41"+
    "\1\12\1\23\1\6\1\34\1\47\1\53\1\6\1\13\1\26\1\50"+
    "\1\25\1\40\1\6\1\24\1\11\1\15\1\37\1\6\1\33\1\6"+
    "\1\56\1\6\4\0\1\7\1\0\1\46\1\57\1\21\1\45\1\17"+
    "\1\27\1\6\1\36\1\51\1\54\1\6\1\20\1\32\1\52\1\31"+
    "\1\44\1\6\1\30\1\16\1\22\1\43\1\6\1\35\1\6\1\60"+
    "\1\6\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\30\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\1"+
    "\1\16\10\4\1\17\22\4\1\20\1\0\1\21\1\4"+
    "\1\22\13\4\1\23\3\4\1\24\15\4\1\25\5\4"+
    "\1\26\5\4\1\27\2\4\1\30\2\4\1\31\1\32"+
    "\4\4\1\33\1\34\1\35\1\36\4\4\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\72\0\256\0\350\0\u0122\0\72"+
    "\0\u015c\0\u0196\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2"+
    "\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2"+
    "\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\u06cc\0\u0706\0\u0740\0\u077a\0\u07b4\0\u07ee\0\u0828\0\u0862"+
    "\0\u089c\0\u08d6\0\u0122\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8"+
    "\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8"+
    "\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0122\0\u06cc\0\72"+
    "\0\u0d24\0\u0122\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80"+
    "\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0122\0\u0fdc\0\u1016"+
    "\0\u1050\0\u0122\0\u108a\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac"+
    "\0\u11e6\0\u1220\0\u125a\0\u1294\0\u12ce\0\u1308\0\u1342\0\u0122"+
    "\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u0122\0\u149e\0\u14d8"+
    "\0\u1512\0\u154c\0\u1586\0\u0122\0\u15c0\0\u15fa\0\u0122\0\u1634"+
    "\0\u166e\0\u0122\0\u0122\0\u16a8\0\u16e2\0\u171c\0\u1756\0\u0122"+
    "\0\u0122\0\u0122\0\u0122\0\u1790\0\u17ca\0\u1804\0\u183e\0\u0122";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\11\2\7\1\12\1\13\1\14\2\7\1\15\1\16"+
    "\1\17\1\7\1\20\1\7\1\21\1\7\1\22\1\7"+
    "\1\23\1\7\1\24\1\7\1\25\1\7\1\26\1\27"+
    "\1\30\1\7\1\31\1\32\1\33\1\7\1\34\1\7"+
    "\1\35\1\36\1\37\1\7\1\40\1\7\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\74\0"+
    "\1\4\77\0\1\52\65\0\2\6\2\0\1\52\65\0"+
    "\4\7\1\0\50\7\15\0\4\7\1\0\1\7\1\53"+
    "\46\7\15\0\4\7\1\0\13\7\1\54\34\7\15\0"+
    "\4\7\1\0\31\7\1\55\16\7\15\0\4\7\1\0"+
    "\6\7\1\56\41\7\15\0\4\7\1\0\17\7\1\57"+
    "\30\7\15\0\4\7\1\0\35\7\1\60\12\7\15\0"+
    "\4\7\1\0\13\7\1\61\34\7\15\0\4\7\1\0"+
    "\13\7\1\62\23\7\1\63\10\7\15\0\4\7\1\0"+
    "\17\7\1\64\30\7\15\0\4\7\1\0\17\7\1\65"+
    "\21\7\1\63\6\7\15\0\4\7\1\0\23\7\1\66"+
    "\24\7\15\0\4\7\1\0\25\7\1\67\22\7\15\0"+
    "\4\7\1\0\1\70\26\7\1\71\20\7\15\0\4\7"+
    "\1\0\1\7\1\72\27\7\1\73\16\7\15\0\4\7"+
    "\1\0\1\74\47\7\15\0\4\7\1\0\5\7\1\75"+
    "\25\7\1\76\14\7\15\0\4\7\1\0\6\7\1\77"+
    "\26\7\1\100\12\7\15\0\4\7\1\0\5\7\1\101"+
    "\42\7\15\0\4\7\1\0\37\7\1\102\10\7\15\0"+
    "\4\7\1\0\41\7\1\103\6\7\15\0\4\7\1\0"+
    "\14\7\1\104\33\7\15\0\4\7\1\0\20\7\1\105"+
    "\27\7\15\0\4\7\1\0\45\7\1\106\2\7\15\0"+
    "\4\7\1\0\47\7\1\106\11\0\71\107\1\110\4\0"+
    "\2\52\70\0\4\7\1\0\2\7\1\111\1\7\1\112"+
    "\43\7\15\0\4\7\1\0\1\7\1\113\46\7\15\0"+
    "\4\7\1\0\44\7\1\114\3\7\15\0\4\7\1\0"+
    "\7\7\1\115\1\7\1\112\36\7\15\0\4\7\1\0"+
    "\6\7\1\116\41\7\15\0\4\7\1\0\46\7\1\117"+
    "\1\7\15\0\4\7\1\0\14\7\1\120\33\7\15\0"+
    "\4\7\1\0\30\7\1\121\17\7\15\0\4\7\1\0"+
    "\20\7\1\122\27\7\15\0\4\7\1\0\34\7\1\123"+
    "\13\7\15\0\4\7\1\0\1\7\1\124\46\7\15\0"+
    "\4\7\1\0\6\7\1\125\41\7\15\0\4\7\1\0"+
    "\1\7\1\126\46\7\15\0\4\7\1\0\30\7\1\127"+
    "\17\7\15\0\4\7\1\0\1\130\47\7\15\0\4\7"+
    "\1\0\4\7\1\131\43\7\15\0\4\7\1\0\3\7"+
    "\1\132\44\7\15\0\4\7\1\0\6\7\1\126\41\7"+
    "\15\0\4\7\1\0\34\7\1\133\13\7\15\0\4\7"+
    "\1\0\5\7\1\134\42\7\15\0\4\7\1\0\11\7"+
    "\1\135\36\7\15\0\4\7\1\0\10\7\1\132\37\7"+
    "\15\0\4\7\1\0\37\7\1\136\10\7\15\0\4\7"+
    "\1\0\41\7\1\137\6\7\15\0\4\7\1\0\36\7"+
    "\1\140\11\7\15\0\4\7\1\0\40\7\1\141\7\7"+
    "\15\0\4\7\1\0\1\7\1\142\46\7\15\0\4\7"+
    "\1\0\31\7\1\143\16\7\15\0\4\7\1\0\2\7"+
    "\1\144\45\7\15\0\4\7\1\0\6\7\1\145\41\7"+
    "\15\0\4\7\1\0\35\7\1\146\12\7\15\0\4\7"+
    "\1\0\7\7\1\147\40\7\15\0\4\7\1\0\15\7"+
    "\1\150\32\7\15\0\4\7\1\0\1\7\1\151\46\7"+
    "\15\0\4\7\1\0\21\7\1\150\26\7\15\0\4\7"+
    "\1\0\6\7\1\152\41\7\15\0\4\7\1\0\13\7"+
    "\1\153\34\7\15\0\4\7\1\0\17\7\1\154\30\7"+
    "\15\0\4\7\1\0\31\7\1\155\16\7\15\0\4\7"+
    "\1\0\3\7\1\156\44\7\15\0\4\7\1\0\31\7"+
    "\1\157\16\7\15\0\4\7\1\0\35\7\1\160\12\7"+
    "\15\0\4\7\1\0\10\7\1\156\37\7\15\0\4\7"+
    "\1\0\35\7\1\161\12\7\15\0\4\7\1\0\1\7"+
    "\1\162\46\7\15\0\4\7\1\0\6\7\1\163\41\7"+
    "\15\0\4\7\1\0\37\7\1\164\10\7\15\0\4\7"+
    "\1\0\41\7\1\164\6\7\15\0\4\7\1\0\3\7"+
    "\1\165\44\7\15\0\4\7\1\0\4\7\1\166\43\7"+
    "\15\0\4\7\1\0\1\7\1\167\46\7\15\0\4\7"+
    "\1\0\10\7\1\170\37\7\15\0\4\7\1\0\11\7"+
    "\1\171\36\7\15\0\4\7\1\0\6\7\1\167\41\7"+
    "\15\0\4\7\1\0\13\7\1\172\34\7\15\0\4\7"+
    "\1\0\17\7\1\172\30\7\15\0\4\7\1\0\1\7"+
    "\1\173\46\7\15\0\4\7\1\0\6\7\1\173\41\7"+
    "\15\0\4\7\1\0\4\7\1\174\43\7\15\0\4\7"+
    "\1\0\44\7\1\175\3\7\15\0\4\7\1\0\11\7"+
    "\1\176\36\7\15\0\4\7\1\0\46\7\1\177\1\7"+
    "\15\0\4\7\1\0\13\7\1\200\34\7\15\0\4\7"+
    "\1\0\17\7\1\200\30\7\15\0\4\7\1\0\4\7"+
    "\1\201\43\7\15\0\4\7\1\0\1\7\1\202\46\7"+
    "\15\0\4\7\1\0\11\7\1\201\36\7\15\0\4\7"+
    "\1\0\6\7\1\202\41\7\15\0\4\7\1\0\1\7"+
    "\1\203\46\7\15\0\4\7\1\0\31\7\1\204\16\7"+
    "\15\0\4\7\1\0\6\7\1\203\41\7\15\0\4\7"+
    "\1\0\35\7\1\205\12\7\15\0\4\7\1\0\1\206"+
    "\47\7\15\0\4\7\1\0\5\7\1\207\42\7\15\0"+
    "\4\7\1\0\1\7\1\210\46\7\15\0\4\7\1\0"+
    "\6\7\1\210\41\7\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6264];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\1\11\30\1\10\11"+
    "\36\1\1\0\1\11\100\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /* Generamos un java_cup.Symbol para guardar el tipo de token encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Caracter ilegal <"+yytext()+">");
          }
        case 32: break;
        case 2: 
          { /* ignora el espacio */
          }
        case 33: break;
        case 3: 
          { System.out.print("ENTERO ");
                            return symbol(sym.ENTERO, Integer.valueOf(yytext()));
          }
        case 34: break;
        case 4: 
          { System.out.print("ID ");
                             return symbol(sym.ID, yytext());
          }
        case 35: break;
        case 5: 
          { System.out.print(". ");
                             return symbol(sym.PUNYO);
          }
        case 36: break;
        case 6: 
          { System.out.print("* ");
                             return symbol(sym.ASTERISCO);
          }
        case 37: break;
        case 7: 
          { System.out.print("= ");
                            return symbol(sym.IGUAL);
          }
        case 38: break;
        case 8: 
          { System.out.print(", ");
                             return symbol(sym.COMA);
          }
        case 39: break;
        case 9: 
          { System.out.print("; ");
                            return symbol(sym.PUNTOYCOMA);
          }
        case 40: break;
        case 10: 
          { System.out.print("( ");
                             return symbol(sym.PAR_A);
          }
        case 41: break;
        case 11: 
          { System.out.print(") ");
                            return symbol(sym.PAR_C);
          }
        case 42: break;
        case 12: 
          { System.out.print("> ");
                            return symbol(sym.MAYOR);
          }
        case 43: break;
        case 13: 
          { System.out.print("< ");
                             return symbol(sym.MENOR);
          }
        case 44: break;
        case 14: 
          { System.out.print("NUREAL ");
                             return symbol(sym.NUREAL, Float.valueOf(yytext()));
          }
        case 45: break;
        case 15: 
          { System.out.print("ON ");
                            return symbol(sym.ON);
          }
        case 46: break;
        case 16: 
          { System.out.print("BY ");
                              return symbol(sym.BY);
          }
        case 47: break;
        case 17: 
          { System.out.print("LITERAL_STR ");
                            return symbol(sym.LITERAL_STR, yytext());
          }
        case 48: break;
        case 18: 
          { System.out.print("SET ");
                             return symbol(sym.SET);
          }
        case 49: break;
        case 19: 
          { System.out.print("USE ");
                            return symbol(sym.USE);
          }
        case 50: break;
        case 20: 
          { System.out.print("ASC ");
                             return symbol(sym.ASC);
          }
        case 51: break;
        case 21: 
          { System.out.print("FROM ");
                              return symbol(sym.FROM);
          }
        case 52: break;
        case 22: 
          { System.out.print("DESC ");
                            return symbol(sym.DESC);
          }
        case 53: break;
        case 23: 
          { System.out.print("JOIN ");
                              return symbol(sym.JOIN);
          }
        case 54: break;
        case 24: 
          { System.out.print("TABLE ");
                           return symbol(sym.TABLE);
          }
        case 55: break;
        case 25: 
          { System.out.print("ORDER ");
                             return symbol(sym.ORDER);
          }
        case 56: break;
        case 26: 
          { System.out.print("WHERE ");
                           return symbol(sym.WHERE);
          }
        case 57: break;
        case 27: 
          { System.out.print("INNER ");
                              return symbol(sym.INNER);
          }
        case 58: break;
        case 28: 
          { System.out.print("SELECT ");
                          return symbol(sym.SELECT);
          }
        case 59: break;
        case 29: 
          { System.out.print("CREATE ");
                              return symbol(sym.CREATE);
          }
        case 60: break;
        case 30: 
          { System.out.print("UPDATE ");
                              return symbol(sym.UPDATE);
          }
        case 61: break;
        case 31: 
          { System.out.print("DATABASE ");
                             return symbol(sym.DATABASE);
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
