
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 13 11:37:04 CST 2026
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 4;
  public static final int FROM = 3;
  public static final int KEY = 30;
  public static final int MENOR = 26;
  public static final int PUNTO = 16;
  public static final int PUNTOYCOMA = 10;
  public static final int DESC = 24;
  public static final int SELECT = 2;
  public static final int INT = 27;
  public static final int IGUAL = 8;
  public static final int ON = 15;
  public static final int ORDER = 21;
  public static final int PAR_C = 12;
  public static final int PAR_A = 11;
  public static final int ID = 33;
  public static final int LITERAL_STR = 34;
  public static final int TABLE = 19;
  public static final int VARCHAR = 28;
  public static final int CREATE = 17;
  public static final int COMA = 9;
  public static final int INNER = 13;
  public static final int MAYOR = 25;
  public static final int BY = 22;
  public static final int EOF = 0;
  public static final int ASTERISCO = 7;
  public static final int DATABASE = 18;
  public static final int SET = 6;
  public static final int error = 1;
  public static final int NUREAL = 32;
  public static final int PRIMARY = 29;
  public static final int ASC = 23;
  public static final int USE = 20;
  public static final int ENTERO = 31;
  public static final int UPDATE = 5;
  public static final int JOIN = 14;
}

