
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 09 17:12:18 CST 2026
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTOYCOMA = 10;
  public static final int DESC = 28;
  public static final int ENTERO = 46;
  public static final int INT = 31;
  public static final int ASTERISCO = 7;
  public static final int UPDATE = 5;
  public static final int WHERE = 4;
  public static final int AND = 44;
  public static final int NOT = 36;
  public static final int IGUAL = 8;
  public static final int USE = 24;
  public static final int OR = 45;
  public static final int REFERENCES = 40;
  public static final int FOREIGN = 39;
  public static final int ON = 15;
  public static final int VARCHAR = 32;
  public static final int SELECT = 2;
  public static final int ID = 48;
  public static final int DECIMAL = 38;
  public static final int EOF = 0;
  public static final int GROUP = 42;
  public static final int BY = 26;
  public static final int TABLE = 23;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int VALUES = 19;
  public static final int NULL = 37;
  public static final int AUTO_INCREMENT = 35;
  public static final int MENOR = 30;
  public static final int LITERAL_STR = 49;
  public static final int JOIN = 14;
  public static final int PAR_C = 12;
  public static final int PAR_A = 11;
  public static final int INNER = 13;
  public static final int FROM = 3;
  public static final int NUREAL = 47;
  public static final int MAYOR = 29;
  public static final int ASC = 27;
  public static final int INTO = 18;
  public static final int PUNTO = 16;
  public static final int CREATE = 21;
  public static final int INSERT = 17;
  public static final int ORDER = 25;
  public static final int FLOAT = 20;
  public static final int DATABASE = 22;
  public static final int KEY = 34;
  public static final int COUNT = 43;
  public static final int AS = 41;
  public static final int PRIMARY = 33;
  public static final int SET = 6;
}

