
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 31 11:34:01 GMT-06:00 2019
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RUSE = 17;
  public static final int DOSPUNTOS = 10;
  public static final int DSTRING = 26;
  public static final int DREAL = 27;
  public static final int PUNTOYCOMA = 2;
  public static final int DREADKEY = 16;
  public static final int ENTERO = 13;
  public static final int DCONST = 23;
  public static final int OP_DIVIDE = 6;
  public static final int OP_MULTI = 5;
  public static final int DCLRSCR = 34;
  public static final int DMATH = 21;
  public static final int DWRITE = 32;
  public static final int DENTERO = 28;
  public static final int PARCIERRA = 9;
  public static final int DDOS = 18;
  public static final int ID = 7;
  public static final int DBEGIN = 30;
  public static final int EOF = 0;
  public static final int DINTEGER = 29;
  public static final int PARIZQ = 11;
  public static final int DCRT = 19;
  public static final int error = 1;
  public static final int OP_RESTA = 4;
  public static final int NPROGRAM = 15;
  public static final int NUREAL = 14;
  public static final int OP_IGUAL = 25;
  public static final int DWRITELN = 33;
  public static final int DEND = 31;
  public static final int DREADLN = 35;
  public static final int SCOMA = 20;
  public static final int PARABRE = 8;
  public static final int DVAR = 24;
  public static final int OP_SUMA = 3;
  public static final int DGRAPH = 22;
  public static final int PARDER = 12;
}

